### ISSUE TITLE
Value type on Chip accepts invalid types. Tighten value types for Chip to match Mantine

### ISSUE THREAD

**Issue by jafin** [aranlucas/react-hook-form-mantine#15]
Mantine Chip accepts value of type `string | number | readonly string[] | undefined`

When using Chip from react-hook-form-mantine it allows setting value to `boolean`

It would be good if there was a way to restrict this type to match Mantine

**Comment by aranlucas** [comment]
This type is inferred from whatever values are passed in from `useForm`. If the values given there are right, then they should be inferred correctly.
