### ISSUE TITLE
Mantine v7

### ISSUE THREAD

**Issue by ncunningham-stairsupplies** [aranlucas/react-hook-form-mantine#17]
can you update to support mantine v7?

**Comment by aranlucas** [comment]
Working on this today :)

**Comment by aranlucas** [comment]
https://github.com/aranlucas/react-hook-form-mantine/releases/tag/v3.1.2

There's quite a couple of breaking changes in v7, make sure to take a look at them.

**Comment by aranlucas** [comment]
I misread migration notes :(

https://mantine.dev/changelog/7-0-0#other-changes -> Transfer list was removed and I thought they were all replaced by combo box.

Added back in https://github.com/aranlucas/react-hook-form-mantine/releases/tag/v3.1.3

**Comment by 06kellyjac** [comment]
Thanks for the swift response. I'll let you know if I spot anything else and maybe put in a PR :)

**Comment by enyelsequeira** [comment]
> Combobox seems to be a big feature of Mantine v7, is it possible to support it somehow? Maybe by wrapping InputBase?

Hey @aranlucas  I have added this in a project I am working on, I could make it here and make a `PR` if you see the value on it

**Comment by sradu** [comment]
@enyelsequeira if you could share the combobox snippet that would be amazing.

**Comment by popuguytheparrot** [comment]
what version for v6?
