### ISSUE TITLE
Refs don't seem to work

### ISSUE THREAD

**Issue by reintroducing** [aranlucas/react-hook-form-mantine#24]
When passing a ref to any of the fields, you get TS errors:
<img width="519" alt="Screenshot 2023-12-15 at 4 27 23 PM" src="https://github.com/aranlucas/react-hook-form-mantine/assets/259901/e43bb3e3-ee75-493c-931e-9de9d947c007">
What is the proper way to apply refs to the components?

**Comment by ivosabev** [comment]
Ref's are not supported from what I see, I copied the source code and added the forwardRef myself.

**Comment by reintroducing** [comment]
> Ref's are not supported from what I see, I copied the source code and added the forwardRef myself.

I considered that approach but that puts management of all the code on you and not this library, which defeats the purpose of installing it in the first place, unfortunately. I've since moved away from this approach and am using mantine/forms instead.
