### ISSUE TITLE
Too strict  `peerDependency` for @mantine/core

### ISSUE THREAD

**Issue by whoisYeshua** [aranlucas/react-hook-form-mantine#3]
Hello. looks like `@mantine/core `should have "`^6.0.0"` instead of `"6.0.0"`
<img width="853" alt="Screenshot 2023-05-08 at 01 35 22" src="https://user-images.githubusercontent.com/56356512/236705850-c3f59841-17d3-4690-b078-0badf66f01b5.png">

**Comment by aranlucas** [comment]
Thanks for the issue and quick fix.

Released in https://www.npmjs.com/package/react-hook-form-mantine/v/1.0.9
