### ISSUE TITLE
Support DatePickerIcon

### ISSUE THREAD

**Issue by otsukatatsuya** [aranlucas/react-hook-form-mantine#7]
support datePickerIcon component please.
https://mantine.dev/dates/date-picker-input/

**Comment by aranlucas** [comment]
This shouldn't be too hard to support. 

I'll probably create another package like react-hook-form-mantine-dates (Turning this into a monorepo). This should also make it easier to add something like dropzones too if needed.

I'm currently busy interviewing and can't make any promises on dates, but I'll work on it as soon as I can.

**Comment by otsukatatsuya** [comment]
Thanks!I hope your intervewing will be succsessful!

**Comment by Muhammad-Arsalan31** [comment]
> This shouldn't be too hard to support.
> 
> I'll probably create another package like react-hook-form-mantine-dates (Turning this into a monorepo). This should also make it easier to add something like dropzones too if needed.
> 
> I'm currently busy interviewing and can't make any promises on dates, but I'll work on it as soon as I can.

Hi @aranlucas ,any update on this. looking forward to this.

**Comment by rommelmamedov** [comment]
Just a heads up. PR for this issue is ready and needs to be reviewed.

**Comment by aranlucas** [comment]
Released in https://github.com/aranlucas/react-hook-form-mantine/releases/tag/v2.0.0.

Let me know how it goes :)

**Comment by aranlucas** [comment]
Closing this issue as completed
